public with sharing class calculator{
    public calculator(){
    }

    public Integer add(Integer a, Integer b){
        return a + b;
    }

    public Integer sub(Integer a, Integer b){
        return (a - b); //
    }

    public Integer mul(Integer a, Integer b){
        return (a * b); //
    }

    //This is Division function
    public Integer div(Integer a, Integer b){
        return (a / b); //
    }
}